name: JMeter Performance Test with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Pull JMeter Docker image
      - name: Pull JMeter Docker image
        run: docker pull justb4/jmeter:5.7.0

      # Step 3: Run JMeter test plan
      - name: Run JMeter Test
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/tests \
            justb4/jmeter:5.7.0 \
            -n -t /tests/my_test_plan.jmx -l /tests/results.jtl

      # Step 4: Generate HTML report
      - name: Generate HTML Report
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/tests \
            justb4/jmeter:5.7.0 \
            -g /tests/results.jtl -o /tests/html-report

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html-report
          publish_branch: gh-pages
          force_orphan: true
