name: JMeter Performance Test with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull JMeter Docker image
        run: docker pull justb4/jmeter:5.5

      - name: Run JMeter Test
        run: |
          # Remove old results file
          rm -f ${{ github.workspace }}/results.jtl
          # Run JMeter test
          docker run --rm \
            -v ${{ github.workspace }}:/mnt/jmeter \
            justb4/jmeter:5.5 \
            -n -t /mnt/jmeter/my_test_plan.jmx -l /mnt/jmeter/results.jtl

      - name: Generate HTML Report
        run: |
          # Remove old HTML report folder
          rm -rf ${{ github.workspace }}/html-report
          # Generate new HTML report
          docker run --rm \
            -v ${{ github.workspace }}:/mnt/jmeter \
            justb4/jmeter:5.5 \
            -g /mnt/jmeter/results.jtl -o /mnt/jmeter/html-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html-report
          force_orphan: true
