name: JMeter Performance Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Download Apache JMeter
      - name: Download Apache JMeter
        run: |
          curl -L -o apache-jmeter.tgz https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.7.0.tgz
          tar -xzf apache-jmeter.tgz
          mv apache-jmeter-5.7.0 apache-jmeter

      # Step 4: Run JMeter test
      - name: Run JMeter Test
        run: |
          ./apache-jmeter/bin/jmeter -n -t my_test_plan.jmx -l results.jtl

      # Step 5: Generate HTML report
      - name: Generate HTML Report
        run: |
          rm -rf html-report
          ./apache-jmeter/bin/jmeter -g results.jtl -o html-report

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html-report
          publish_branch: gh-pages
          force_orphan: true
